server:
  port: 20000
  error:
    include-message: always
spring:
  application:
    name: coupon-template-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coupon?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: taylor18
    hikari:
      pool-name:  couponTemplateHikari
      connection-timeout: 5000
      idle-timeout: 3000
      minimum-idle: 5
      maximum-pool-size: 10
      max-lifetime: 60000
      auto-commit: true
  jpa:
    show-sql: true
    # 在生产环境全部为none，防止ddl结构被自动执行
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8948
        # 服务注册到nacos的名称
        service: coupon-template-service
        #客户端向服务端发送心跳的时间间隔，单位ms
        heart-beat-interval: 5000
        #服务端没有接受到客户端心跳请求就将其设为不健康的时间间隔，默认为15s
        # 注：推荐值该值为15s即可，如果有的业务线希望服务下线或者出故障时希望尽快被发现，可以适当减少该值
        heart-beat-timeout: 20000
        #元数据，自己定义
        metadata:
          mydata: Mckenna

        # 客户端在启动时是否读取本地配置项(一个文件)来获取服务列表
        # 注：推荐该值为false，若改成true。则客户端会在本地的一个文件中保存服务信息，当下次宕机启动时，会优先读取本地的配置对外提供服务。
        naming-load-cache-at-start: false

        #命名空间ID，区分环境进行数据隔离
        namespace: dev
        #两个服务存在上下游调用时，必须配置相同的group才能发起调用
        group: Mckenna-Group
        cluster-name: Cluster-A
        #向注册中心注册，默认true；若只作为消费者时，不作为服务提供方，可设置为false
        register-enabled: true
        username: nacos
        password: nacos

    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
        #Sentinel Web filter 默认收敛所有 URL 的入口 context，因此链路限流不生效。设置为false，可根据不同的 URL 进行链路限流
      web-context-unify: false

#    sleuth:
#      sampler:
        #采样率0～1，1表示对请求进行100%采样。小于1说明有的请求不会被采样
#        probability: 1
        # 每秒对1000个request进行采样，请求超过此值，仍会被正常处理，但是调用链信息不会被采样
#        rate: 1000

    alibaba:
      seata:
        tx-service-group: seata-server-group
seata:
  application-id: coupon-template-service
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:8848
      namespace: dev
      group: Mckenna-Group
      username: nacos
      password: nacos
  service:
    vgroup-mapping:
      seata-server-group: default